In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("../data/predictive_maintenance.csv")
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  
0                    1551         42.8                0       0   No Failure  
1                    1408         46.3                3       0   No Failure  
2                    1498         49.4                5       0   No Failure  
3                    1433         39.5                7       0   No Failure  
4                    1408         40.0                9       0   No Failure

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   UDI                      10000 non-null  int64  
 1   Product ID               10000 non-null  object 
 2   Type                     10000 non-null  object 
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64  
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64  
 8   Target                   10000 non-null  int64  
 9   Failure Type             10000 non-null  object 
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB


In [5]:
df.columns = df.columns.str.lower()

In [6]:
df.shape

(10000, 10)

In [7]:
df.duplicated().sum()

np.int64(0)

## Drop unneccassary column 

In [8]:
df.drop( 'udi' , axis=1,  inplace=True)

In [9]:
df.head()

product id type  air temperature [k]  process temperature [k]  \
0     M14860    M                298.1                    308.6   
1     L47181    L                298.2                    308.7   
2     L47182    L                298.1                    308.5   
3     L47183    L                298.2                    308.6   
4     L47184    L                298.2                    308.7   

   rotational speed [rpm]  torque [nm]  tool wear [min]  target failure type  
0                    1551         42.8                0       0   No Failure  
1                    1408         46.3                3       0   No Failure  
2                    1498         49.4                5       0   No Failure  
3                    1433         39.5                7       0   No Failure  
4                    1408         40.0                9       0   No Failure

## inspect for outliers or error in  columns 

In [10]:
df.describe()

air temperature [k]  process temperature [k]  rotational speed [rpm]  \
count         10000.000000             10000.000000            10000.000000   
mean            300.004930               310.005560             1538.776100   
std               2.000259                 1.483734              179.284096   
min             295.300000               305.700000             1168.000000   
25%             298.300000               308.800000             1423.000000   
50%             300.100000               310.100000             1503.000000   
75%             301.500000               311.100000             1612.000000   
max             304.500000               313.800000             2886.000000   

        torque [nm]  tool wear [min]        target  
count  10000.000000     10000.000000  10000.000000  
mean      39.986910       107.951000      0.033900  
std        9.968934        63.654147      0.180981  
min        3.800000         0.000000      0.000000  
25%       33.200000        53.000000      0.000000  
50%       40.100000       108.000000      0.000000  
75%       46.800000       162.000000      0.000000  
max       76.600000       253.000000      1.000000

## product id 

In [11]:
df['product id'].value_counts()

product id
M14860    1
L47181    1
L47182    1
L47183    1
L47184    1
         ..
M24855    1
H39410    1
M24857    1
H39412    1
M24859    1
Name: count, Length: 10000, dtype: int64

In [12]:
df['product id'].nunique()

10000

In [13]:
df['product id'].isna().sum()

np.int64(0)

In [14]:
df.drop('product id', axis=1 , inplace=True)

## type

In [15]:
df['type'].unique()

array(['M', 'L', 'H'], dtype=object)

In [16]:
df['type'].value_counts()

type
L    6000
M    2997
H    1003
Name: count, dtype: int64

In [17]:
df['type'].isnull().sum()

np.int64(0)

## air temperature

In [18]:
df['air temperature [k]'].unique()

array([298.1, 298.2, 298.3, 298.5, 298.4, 298.6, 298.7, 298.8, 298.9,
       299. , 299.1, 298. , 297.9, 297.8, 297.7, 297.6, 297.5, 297.4,
       297.3, 297.2, 297.1, 297. , 296.9, 296.8, 296.7, 296.6, 296.5,
       296.3, 296.4, 296.2, 296.1, 296. , 295.9, 295.8, 295.7, 295.6,
       295.5, 295.4, 295.3, 299.2, 299.3, 299.5, 299.4, 299.6, 299.7,
       299.8, 299.9, 300. , 300.1, 300.2, 300.3, 300.4, 300.5, 300.6,
       300.7, 300.8, 300.9, 301. , 301.1, 301.2, 301.3, 301.4, 301.5,
       301.6, 301.7, 301.8, 301.9, 302. , 302.1, 302.2, 302.3, 302.4,
       302.5, 302.6, 302.7, 302.8, 302.9, 303. , 303.1, 303.2, 303.3,
       303.4, 303.5, 303.6, 303.7, 303.8, 303.9, 304. , 304.1, 304.2,
       304.3, 304.4, 304.5])

In [19]:
df['air temperature [k]'].nunique()

93

In [20]:
df['air temperature [k]'].value_counts()

air temperature [k]
300.7    279
298.9    231
297.4    230
300.5    229
298.8    227
        ... 
304.4      7
296.0      6
295.3      3
295.4      3
304.5      1
Name: count, Length: 93, dtype: int64

In [21]:
df['air temperature [k]'].isna().sum()

np.int64(0)

In [22]:
df.rename(columns={'air temperature [k]' : 'air_temperature'}, inplace=True)

## Process temperature

In [23]:
df['process temperature [k]'].nunique()

82

In [24]:
df['process temperature [k]'].unique()

array([308.6, 308.7, 308.5, 309. , 308.9, 309.1, 309.2, 309.3, 309.4,
       309.5, 308.8, 308.4, 308.3, 308.2, 308.1, 308. , 307.9, 309.6,
       309.7, 309.8, 309.9, 310. , 310.1, 310.2, 307.8, 307.7, 307.6,
       307.5, 307.4, 307.3, 307.2, 307.1, 307. , 306.9, 306.8, 306.7,
       306.6, 306.5, 306.4, 306.3, 306.2, 306.1, 306. , 305.9, 305.8,
       305.7, 310.3, 310.4, 310.5, 310.6, 310.7, 310.8, 310.9, 311. ,
       311.1, 311.2, 311.3, 311.4, 311.5, 311.6, 311.7, 311.8, 311.9,
       312. , 312.1, 312.2, 312.3, 312.4, 312.5, 312.6, 312.7, 312.8,
       313. , 313.1, 312.9, 313.2, 313.3, 313.4, 313.5, 313.6, 313.8,
       313.7])

In [25]:
df['process temperature [k]'].value_counts()

process temperature [k]
310.6    317
310.8    273
310.7    266
308.6    265
310.5    263
        ... 
306.9      4
313.7      4
305.8      3
305.7      2
313.8      2
Name: count, Length: 82, dtype: int64

In [26]:
df.rename(columns={'process temperature [k]' : 'process_temp'}, inplace=True)

In [27]:
df['process_temp'].isna().sum()

np.int64(0)

## rotational speed

In [28]:
df['rotational speed [rpm]'].value_counts()

rotational speed [rpm]
1452    48
1435    43
1447    42
1479    40
1429    40
        ..
2065     1
2710     1
2004     1
1835     1
2144     1
Name: count, Length: 941, dtype: int64

In [29]:
df['rotational speed [rpm]'].nunique()

941

In [30]:
df['rotational speed [rpm]'].unique()

array([1551, 1408, 1498, 1433, 1425, 1558, 1527, 1667, 1741, 1782, 1423,
       1339, 1742, 2035, 1542, 1311, 1410, 1306, 1632, 1375, 1450, 1581,
       1758, 1561, 1861, 1512, 1811, 1439, 1693, 1798, 1419, 1665, 1559,
       1452, 1379, 1350, 1362, 1368, 1372, 1472, 1489, 1843, 1418, 1412,
       2861, 1383, 1497, 1565, 1691, 1477, 1513, 1661, 1378, 1393, 1592,
       1829, 1812, 1523, 1394, 1679, 1466, 1924, 1369, 1601, 1461, 1455,
       1398, 1402, 1445, 1453, 1469, 1422, 1804, 1436, 1544, 1487, 1753,
       1830, 1727, 1622, 1351, 1575, 1750, 1529, 1852, 1991, 1555, 1441,
       1591, 1621, 1572, 1872, 1499, 1486, 1680, 1431, 1564, 1599, 1707,
       1467, 1310, 1546, 1560, 1329, 1413, 1587, 1473, 1737, 1430, 1711,
       1420, 1297, 1449, 1268, 1511, 1778, 1407, 1391, 1612, 1515, 1463,
       1584, 1850, 1528, 1987, 1495, 1478, 1471, 1282, 1586, 1468, 1440,
       1733, 1458, 1318, 1610, 1462, 1382, 1618, 1988, 1304, 1475, 1824,
       1342, 1485, 1446, 1301, 1606, 1539, 1666, 16

In [31]:
df['rotational speed [rpm]'].isna().sum()

np.int64(0)

In [32]:
df.rename(columns={'rotational speed [rpm]' : 'rotational_speed_[rpm]'}, inplace=True)

## torque

In [33]:
df['torque [nm]'].nunique()

577

In [34]:
df['torque [nm]'].unique()

array([42.8, 46.3, 49.4, 39.5, 40. , 41.9, 42.4, 40.2, 28.6, 28. , 23.9,
       44.3, 51.1, 30. , 19.6, 48.4, 46.6, 45.6, 54.5, 32.5, 42.7, 44.8,
       30.7, 25.7, 37.3, 23.3, 39. , 24.6, 44.2, 30.1, 48.2, 25.5, 48.3,
       34.7, 48.6, 36.7, 39.2, 50.7, 52.5, 45.4, 50.8, 49.1, 48.5, 47.5,
       25.8, 53.9, 44.1,  4.6, 54.9, 43.8, 35.1, 40.7, 40.3, 29.5, 54.4,
       52.6, 38.2, 22.9, 25.9, 38.6, 45.1, 28.7, 32.4, 65.7, 22.6, 45.5,
       44.4, 35. , 32.3, 46.7, 47.9, 41.3, 51.5, 37.9, 49.9, 40.8, 40.1,
       47.6, 26.8, 43.9, 31.8, 45.2, 24.9, 27.1, 43. , 31.9, 52.2, 35.3,
       29.9, 32.7, 25. , 20.7, 40.6, 40.5, 43.4, 31.1, 46.8, 34.1, 22.5,
       43.5, 29.4, 45.7, 33. , 28.1, 44.7, 41.2, 32.2, 60.5, 46.5, 34.3,
       41.1, 27.7, 43.2, 49.6, 53. , 28.5, 55.3, 55.8, 36.1, 35.2, 28.2,
       50.5, 33.6, 48. , 39.9, 37.6, 41. , 27. , 36.2, 19.8, 46. , 47. ,
       60.7, 52.3, 35.5, 43.6, 26. , 32.6, 42.9, 62.3, 59.1, 20.8, 33.7,
       58.3, 21.4, 50.2, 49.8, 24.2, 48.1, 30.6, 56

In [35]:
df['torque [nm]'].isnull().sum()

np.int64(0)

In [36]:
df.rename(columns={'torque [nm]': 'torque_[nm]'} , inplace=True)

## tool wear

In [37]:
df['tool wear [min]'].nunique()

246

In [38]:
df['tool wear [min]'].unique()

array([  0,   3,   5,   7,   9,  11,  14,  16,  18,  21,  24,  29,  34,
        37,  40,  42,  44,  47,  50,  55,  58,  63,  65,  68,  70,  73,
        75,  77,  82,  84,  86,  89,  91,  93,  95,  98, 101, 104, 106,
       111, 113, 115, 117, 120, 125, 128, 130, 133, 135, 140, 143, 145,
       147, 152, 154, 156, 158, 160, 162, 165, 167, 169, 172, 174, 177,
       179, 181, 184, 189, 191, 193, 196, 198, 200, 202, 204, 206, 208,
         2,   4,  13,  15,  17,  20,  25,  27,  30,  33,  35,  53,  57,
        59,  61,  66,  72,  80,  92,  97,  99, 103, 108, 110, 112, 114,
       116, 118, 122, 124, 126, 132, 138, 148, 150, 155, 157, 159, 161,
       164, 186, 188, 194, 203, 211, 214, 216, 218,   8,  10,  22,  32,
        39,  41,  43,  45,  49,  54,  67,  69,  74,  76,  81,  96, 105,
       107, 119, 137, 142, 144, 146, 151, 153, 166, 168, 170, 173, 175,
       183, 185, 190, 195, 197, 209, 212,  19,  51,  56,  78,  83,  85,
        88,  90,  94, 109, 131, 134, 136, 192, 199, 201, 205, 21

In [39]:
df['tool wear [min]'].value_counts()

tool wear [min]
0      120
2       69
5       63
7       58
59      58
      ... 
237      1
239      1
241      1
251      1
253      1
Name: count, Length: 246, dtype: int64

In [40]:
df['tool wear [min]'].isna().sum()

np.int64(0)

In [41]:
df.rename(columns={'tool wear [min]': 'tool_wear_[min]'}, inplace=True)

## target

In [42]:
df['target'].value_counts()

target
0    9661
1     339
Name: count, dtype: int64

In [43]:
df['target'].isna().sum()

np.int64(0)

## Failure type 

In [44]:
df['failure type'] = df['failure type'].str.lower()

In [45]:
df['failure type'].value_counts()

failure type
no failure                  9652
heat dissipation failure     112
power failure                 95
overstrain failure            78
tool wear failure             45
random failures               18
Name: count, dtype: int64

In [55]:
df[ (df['target'] == 0) & (df['failure type'] != 'no failure')]

type  air_temperature  process_temp  rotational_speed_[rpm]  torque_[nm]  \
1221    M            297.0         308.3                    1399         46.4   
1302    L            298.6         309.8                    1505         45.7   
1748    H            298.4         307.7                    1626         31.1   
2072    L            299.6         309.5                    1570         35.5   
2559    L            299.3         309.0                    1447         50.4   
3065    M            300.1         309.2                    1687         27.7   
3452    H            301.6         310.5                    1602         32.3   
5471    L            302.7         312.3                    1346         61.2   
5489    L            302.6         312.1                    1499         35.0   
5495    H            302.9         312.5                    1357         55.0   
5509    L            302.8         312.2                    1509         36.5   
5553    L            302.5         311.9                    1306         59.7   
5639    L            302.6         312.1                    1668         28.7   
6091    L            300.9         310.7                    1412         57.5   
6913    L            300.8         311.2                    1481         38.5   
6960    L            300.7         311.0                    1413         52.0   
7488    L            300.3         311.7                    1545         43.5   
7868    H            300.4         311.9                    1438         46.7   

      tool_wear_[min]  target     failure type  
1221              132       0  random failures  
1302              144       0  random failures  
1748              166       0  random failures  
2072              189       0  random failures  
2559              140       0  random failures  
3065               95       0  random failures  
3452                2       0  random failures  
5471              170       0  random failures  
5489              215       0  random failures  
5495               12       0  random failures  
5509               52       0  random failures  
5553              172       0  random failures  
5639              180       0  random failures  
6091               16       0  random failures  
6913              181       0  random failures  
6960               91       0  random failures  
7488              160       0  random failures  
7868               41       0  random failures

In [57]:
df.rename(columns={'failure type': 'failure_type'}, inplace=True)

## Load the data

In [60]:
df.to_csv('../data/preprocessed_predictive_maintenance.csv', index=False)

In [ ]:
pd.read_csv('../data/preprocessed_predictive_maintenance.csv')

type  air_temperature  process_temp  rotational_speed_[rpm]  torque_[nm]  \
0       M            298.1         308.6                    1551         42.8   
1       L            298.2         308.7                    1408         46.3   
2       L            298.1         308.5                    1498         49.4   
3       L            298.2         308.6                    1433         39.5   
4       L            298.2         308.7                    1408         40.0   
...   ...              ...           ...                     ...          ...   
9995    M            298.8         308.4                    1604         29.5   
9996    H            298.9         308.4                    1632         31.8   
9997    M            299.0         308.6                    1645         33.4   
9998    H            299.0         308.7                    1408         48.5   
9999    M            299.0         308.7                    1500         40.2   

      tool_wear_[min]  target failure_type  
0                   0       0   no failure  
1                   3       0   no failure  
2                   5       0   no failure  
3                   7       0   no failure  
4                   9       0   no failure  
...               ...     ...          ...  
9995               14       0   no failure  
9996               17       0   no failure  
9997               22       0   no failure  
9998               25       0   no failure  
9999               30       0   no failure  

[10000 rows x 8 columns]